"""empty message

Revision ID: 208514278827
Revises: 
Create Date: 2020-01-21 22:44:44.635329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208514278827'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_day', sa.String(length=200), nullable=False),
    sa.Column('second_day', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_name', sa.String(length=68), nullable=False),
    sa.Column('recycle', sa.String(length=68), nullable=False),
    sa.Column('reuse', sa.String(length=68), nullable=False),
    sa.Column('reduce', sa.String(length=68), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource__centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('zip', sa.Integer(), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('types', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('zip', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('resource__centers')
    op.drop_table('objects')
    op.drop_table('days')
    # ### end Alembic commands ###
